Fix thread-safety issues in WriterFactory
 - Don't use double checked locking. The underlying cache isn't thread safe, and even if it were, due to evictions unsynchronized access can result in calling `new WriteHandlerMap(null)`
 - Never return the `WriteHandlerMap` that gets stored in the cache. `WriteHandlerMap`s are effectively mutable which can cause exceptions if the returned copy gets mutated by a different thread while another writer is being created.

Example exception this fixes:
```
                                cognitect.transit/writer               transit.clj:  143
             com.cognitect.transit.TransitFactory.writer       TransitFactory.java:   62
com.cognitect.transit.impl.WriterFactory.getJsonInstance        WriterFactory.java:   52
     com.cognitect.transit.impl.WriterFactory.handlerMap        WriterFactory.java:   31
       com.cognitect.transit.impl.WriteHandlerMap.<init>      WriteHandlerMap.java:   83
                                java.util.HashMap.putAll              HashMap.java:  784
                         java.util.HashMap.putMapEntries              HashMap.java:  511
                    java.util.HashMap$EntryIterator.next              HashMap.java: 1469
                    java.util.HashMap$EntryIterator.next              HashMap.java: 1471
                 java.util.HashMap$HashIterator.nextNode              HashMap.java: 1437
java.util.ConcurrentModificationException:
               java.lang.RuntimeException: java.util.ConcurrentModificationException
```